#!/usr/bin/env python

"""
Copyright(c)2009 Internet Archive. Software license AGPL version 3.

This file is part of bookserver.

    bookserver is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bookserver is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with bookserver.  If not, see <http://www.gnu.org/licenses/>.
    
    The bookserver source is hosted at http://github.com/internetarchive/bookserver/

"""

# This function was copied from http://github.com/internetarchive/epub/blob/master/iarchive.py
# Adapted from http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
def iso_639_23_to_iso_639_1(marc_code):
    mapping = {
        'aar':'aa',
        'abk':'ab',
        'ave':'ae',
        'afr':'af',
        'aka':'ak',
        'amh':'am',
        'arg':'an',
        'ara':'ar',
        'asm':'as',
        'ava':'av',
        'aym':'ay',
        'aze':'az',
        'bak':'ba',
        'bel':'be',
        'bul':'bg',
        'bih':'bh',
        'bis':'bi',
        'bam':'bm',
        'ben':'bn',
        'bod':'bo',
        'tib':'bo',
        'bre':'br',
        'bos':'bs',
        'cat':'ca',
        'che':'ce',
        'cha':'ch',
        'cos':'co',
        'cre':'cr',
        'ces':'cs',
        'cze':'vs',
        'chu':'cu',
        'chv':'cv',
        'cym':'cy',
        'wel':'cy',
        'dan':'da',
        'deu':'de',
        'ger':'de',
        'div':'dv',
        'dzo':'dz',
        'ewe':'ee',
        'ell':'el',
        'gre':'el',
        'eng':'en',
        'epo':'eo',
        'spa':'es',
        'est':'et',
        'eus':'eu',
        'baq':'eu',
        'fas':'fa',
        'per':'fa',
        'ful':'ff',
        'fin':'fi',
        'fij':'fj',
        'fao':'fo',
        'fra':'fr',
        'fre':'fr',
        'fry':'fy',
        'gle':'ga',
        'gla':'gd',
        'glg':'gl',
        'grn':'gn',
        'guj':'gu',
        'glv':'gv',
        'hau':'ha',
        'heb':'he',
        'hin':'hi',
        'hmo':'ho',
        'hrv':'hr',
        'cro':'hr', #IA special case: some libraries use 'cro' instead of 'hrv' in marc records for Croatian
        'hat':'ht',
        'hun':'hu',
        'hye':'hy',
        'arm':'hy',
        'her':'hz',
        'ina':'ia',
        'ind':'id',
        'ile':'ie',
        'ibo':'ig',
        'iii':'ii',
        'ipk':'ik',
        'ido':'io',
        'isl':'is',
        'ice':'is',
        'ita':'it',
        'iku':'iu',
        'jpn':'ja',
        'jav':'jv',
        'kat':'ka',
        'geo':'ka',
        'kon':'kg',
        'kik':'ki',
        'kua':'kj',
        'kaz':'kk',
        'kal':'kl',
        'khm':'km',
        'kan':'kn',
        'kor':'ko',
        'kau':'kr',
        'kas':'ks',
        'kur':'ku',
        'kom':'kv',
        'cor':'kw',
        'kir':'ky',
        'lat':'la',
        'ltz':'lb',
        'lug':'lg',
        'lim':'li',
        'lin':'ln',
        'lao':'lo',
        'lit':'lt',
        'lub':'lu',
        'lav':'lv',
        'mlg':'mg',
        'mah':'mh',
        'mri':'mi',
        'mao':'mi',
        'mkd':'mk',
        'mac':'mk',
        'mal':'ml',
        'mon':'mn',
        'mar':'mr',
        'msa':'ms',
        'may':'ms',
        'mlt':'mt',
        'mya':'my',
        'bur':'my',
        'nau':'na',
        'nob':'nb',
        'nde':'nd',
        'nep':'ne',
        'ndo':'ng',
        'nld':'nl',
        'dut':'nl',
        'nno':'nn',
        'nor':'no',
        'nbl':'nr',
        'nav':'nv',
        'nya':'ny',
        'oci':'oc',
        'oji':'oj',
        'orm':'om',
        'ori':'or',
        'oss':'os',
        'pan':'pa',
        'pli':'pi',
        'pol':'pl',
        'pus':'ps',
        'por':'pt',
        'que':'qu',
        'roh':'rm',
        'run':'rn',
        'ron':'ro',
        'rum':'ro',
        'rus':'ru',
        'kin':'rw',
        'san':'sa',
        'srd':'sc',
        'snd':'sd',
        'sme':'se',
        'sag':'sg',
        'sin':'si',
        'slk':'sk',
        'slo':'sk',
        'slv':'sl',
        'smo':'sm',
        'sna':'sn',
        'som':'so',
        'sqi':'sq',
        'alb':'sq',
        'srp':'sr',
        'ssw':'ss',
        'sot':'st',
        'sun':'su',
        'swe':'sv',
        'swa':'sw',
        'tam':'ta',
        'tel':'te',
        'tgk':'tg',
        'tha':'th',
        'tir':'ti',
        'tuk':'tk',
        'tgl':'tl',
        'tsn':'tn',
        'ton':'to',
        'tur':'tr',
        'tso':'ts',
        'tat':'tt',
        'twi':'tw',
        'tah':'ty',
        'uig':'ug',
        'ukr':'uk',
        'urd':'ur',
        'uzb':'uz',
        'ven':'ve',
        'vie':'vi',
        'vol':'vo',
        'wln':'wa',
        'wol':'wo',
        'xho':'xh',
        'yid':'yi', 
        'yor':'yo',
        'zha':'za',
        'zho':'zh',
        'chi':'zh',
        'zul':'zu',
        }
    if marc_code in mapping:
        return mapping[marc_code]
    else:
        return marc_code